package data.entities;

import androidx.room.Entity;
import androidx.room.PrimaryKey;

import java.util.Date;

@Entity(tableName = "treatments")
public class TreatmentEntity {

    @PrimaryKey(autoGenerate = true)
    private long treatmentId;

    private long patientId;

    private String disease;
    private String prescription;
    private Date date;

    // Room will use this constructor (or you can add @Ignore constructors as needed)
    public TreatmentEntity(long patientId, String disease, String prescription, Date date) {
        this.patientId   = patientId;
        this.disease     = disease;
        this.prescription = prescription;
        this.date        = date;
    }

    // Required zero-arg constructor if Room needs it
    public TreatmentEntity() { }

    // Getters (must match exactly in your adapter/DAO code)
    public long   getTreatmentId() { return treatmentId; }
    public long   getPatientId()   { return patientId;   }
    public String getDisease()     { return disease;     }
    public String getPrescription(){ return prescription;}
    public Date   getDate()        { return date;        }

    // Setters (needed for Room to set the autogenerated PK, etc.)
    public void setTreatmentId(long treatmentId) { this.treatmentId = treatmentId; }
    public void setPatientId(long patientId)     { this.patientId = patientId;     }
    public void setDisease(String disease)       { this.disease = disease;         }
    public void setPrescription(String prescription) { this.prescription = prescription; }
    public void setDate(Date date)               { this.date = date; }
}

